# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 07:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160522_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='parkings',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
    ]
